### ISSUE TITLE
Hey Arihant, I'm a fellow UGEE aspirant. interested in CSE just like you. I would really appreciate guidance from you. I wrote my 10th boards a week ago.

### ISSUE THREAD

**Issue by Devesh-N** [Arihant25/grades-calculator-iiith#1]
You can check out my Github profile to see the projects I have done(some of them are private)
A little bit about me:
I'm 15
I know Python pretty well and I am currently doing DevOps and I plan to do CKAD certification soon.
Hoping to connect with you ;)
P.S I found you from the article you wrote in medium
@Arihant25

**Comment by Arihant25** [comment]
Hi, Devesh. You can contact me on Instagram, making GitHub issues on my repositories isn't the best way to contact me you know? :)
