### ISSUE TITLE
Scrolling up / down when filling in marks increases / decreases it

### ISSUE THREAD

**Issue by aryan12cc** [Arihant25/grades-calculator-iiith#3]
When I have a field open (eg quiz 1 in LA) and scroll up / down inside the tab, it increases / decreases my marks written inside the field (or takes it as 0 if unfilled). This is particularly annoying when I scroll down to fill in more data.

**Comment by Arihant25** [comment]
Numbers changing in forms on scrolling is the default behaviour for HTML, but anyways, I have removed that now. Also, the form values turn into zero if unfilled to indicate that the value has been taken as zero for the final calculation.
